### ISSUE TITLE
Users are able to continue and go to the next page without accepting the terms and conditions of the warning

### ISSUE THREAD

**Issue by Jingwnpn** [KSJI/alpha#5] opened 2018-06-04 01:38 UTC
After signing up, it brought me to this warning page. However, I am able to click the Continue button to go to the next page without checking the box and accepting the terms and conditions of this warning.

<img width="1041" alt="screen shot 2018-06-03 at 6 37 00 pm" src="https://user-images.githubusercontent.com/22405025/40894269-4a810486-675d-11e8-9662-154c83413e4d.png">

**Comment by MirelesI** [comment] 2018-06-05 08:38
I was unable to confirm this bug. When I press the continue button in that state I am taken back to the sign-in page, was there anything else you did?

**Comment by soobkwon** [comment] 2018-06-05 19:57
Also if it returns you back to the sign-in page that is correct. We want our users to read this warning and accept the conditions before they can begin to use our website. We have tried on multiple accounts and computers and could not reproduce this bug as we were redirected back to the correct page. So for now we are going to close this case.

**Closed as completed by soobkwon** 2018-06-05 19:57 UTC

**Comment by abegel** [comment] 2018-06-06 05:39
@Jingwnpn Can you reproduce this bug?

**Comment by Jingwnpn** [comment] 2018-06-06 17:35
Yes, when you click the Continue button, it does direct you to the sign-in page. However, the issue I was stating is that users are allowed to continue WITHOUT CHECKING THE BOX for 'I accept the terms and conditions of this warning.' That means even though users have seen the warning, it does not necessarily mean they accept the warning if they did not check the box. I believe it could lead to legal issues. Therefore, I flagged this as an issue. I hope this clarifies your confusion. Please let me know if you have more questions regarding this issue.

**Comment by abegel** [comment] 2018-06-07 04:51
@MirelesI @soobkwon Your thoughts?

**Comment by soobkwon** [comment] 2018-06-07 06:18
We intentionally re-direct our users back to the sign-in page if they do not accept the terms and condition. If users do not accept that page, it will appear until they do so. It is an important message that we want our users to be aware of before they begin using our product. I understand what your concern is, but we want to bring attention by acknowledging this issue that users could be using our website for bad intent. If anything this could help us with legal issues if a user does take our website too extreme and decide to blame or sue us for their outcome in becoming bulimic, anorexic, or etc. This warning was meant to have our users be aware and to hopefully remember that this website is meant to encourage healthy lifestyles and to be used for fun. Hence why we want our users to accept the warning in order to verify that they do have the right mindset to continue using our product appropriately.
